Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "vm1"
  config.vm.network "private_network", ip: "192.168.1.11"
  config.vm.synced_folder "../data", "/home/vagrant/data"
  config.vm.provision "file", source:"copiedfile.txt" , destination: "/home/vagrant/copiedfile.txt"
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["modifyvm", :id, "--cpues", 4]
  end
end
