Vagrant.configure("2") do |config|
    servers=[
        {
          :hostname => "AppServer1",
          :box => "bento/ubuntu-18.04",
          :ip => "172.16.1.50",
          :ssh_port => '2201'
        },
        {
          :hostname => "AppServer2",
          :box => "bento/ubuntu-18.04",
          :ip => "172.16.1.51",
          :ssh_port => '2202'
        },
        {
          :hostname => "WebServer1",
          :box => "bento/ubuntu-18.04",
          :ip => "172.16.2.50",
          :ssh_port => '2210'
        },
        {
          :hostname => "WebServer2",
          :box => "bento/ubuntu-18.04",
          :ip => "172.16.2.51",
          :ssh_port => '2211'
        },
        {
          :hostname => "DBServer1",
          :box => "bento/centos-7.2",
          :ip => "172.16.3.50",
          :ssh_port => '2220'
        },
        {
          :hostname => "DBServer2",
          :box => "bento/centos-7.2",
          :ip => "172.16.3.51",
          :ssh_port => '2221'
        }
      ]

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.synced_folder "../data", "/home/vagrant/data"
            node.vm.provision "file", source: "./copiedfile.txt", destination: "/home/vagrant/copiedfile.txt"

            node.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", 512]
                vb.customize ["modifyvm", :id, "--cpus", 2]
            end
        end
    end
end
